services:
  snapcast:
    image: ghcr.io/yubiuser/librespot-shairport-snapserver:latest
    container_name: snapcast
    restart: unless-stopped
    network_mode: host
    volumes:
     - ./snapserver.conf:/etc/snapserver.conf
     - ./shairport-sync.conf:/etc/shairport-sync.conf
     - /etc/localtime:/etc/localtime:ro
     #- /tmp/snapfifo:/tmp/snapfifo
