#!/command/with-contenv sh
while [ ! -f /var/run/avahi-daemon/pid ]; do
  echo "s6-rc: warning: avahi is not running, sleeping for 5 seconds before trying to start snapserver"
  sleep 5
done
echo "Starting snapserver"
exec /usr/local/bin/snapserver
